### PR TITLE
Fixed print_time bug.

### PR DESCRIPTION
**Pull request by mspandit**

### CODE REVIEW

**Comment by mspandit** [comment]
Any questions or concerns about this pull request? Or have you stopped maintaining this project?

**Comment by rafacarrascosa** [comment]
Damn! I'm really sorry about this! It just slipped away from us.
One concern only: Please make the pull request agains develop instead of master... please?
Thank you!

**Comment by mspandit** [comment]
OK, no problem. Thank you.

**Comment by mspandit** [comment]
Closing this and opening a new one against develop.

**Pull request closed without merging**
